### ISSUE TITLE
Unfinished thought on "Make the invisible, visible"

### ISSUE THREAD

**Issue by jamisonbryant** [PrinciplesDotDev/principles#28]
How section, Code subsection, final bullet in the list. Looks like you forgot to finish your...

<details>
  <summary>Click to reveal the joke</summary>
  
  `sentence.`
</details>

**Comment by AdamCraven** [comment]
Thank you @jamisonbryant  - fixed.

**Comment by AdamCraven** [comment]
https://principles.dev/p/make-the-invisible-visible/
