### ISSUE TITLE
Need ability to relate Principles

### ISSUE THREAD

**Issue by dexterous** [PrinciplesDotDev/principles#30]
For instance, single-responsibility-principle can be used as a tool to effectively drive reduce-a-problem-to-its-lowest-sensible-abstraction.

**Comment by AdamCraven** [comment]
Tell me more @dexterous. How do you see it driving that behavior? And do you see the relationships working as a tree, siblings, priority order, etc..?

I'm developing (https://github.com/PrinciplesDotDev/principles/discussions/20) principles list functionality will allow grouping the principles together and assigning priority order. And in the yet unfinished principle driven engineering, "Emergent behavior" - which is the interaction of principles to create more complex behavior, may cover what you are thinking

**Comment by dexterous** [comment]
> Tell me more @dexterous. How do you see it driving that behavior?

Similar to the example I presented above, I'd say we can find examples of principles that are statements of other principles in specific contexts or principles that can be bolstered by others. I'll have to go through the list to come up with specific instances of relationships.

> do you see the relationships working as a tree

I'd say it'd be more of a graph because I'm sure some of the relationships could well be cyclic.

> "Emergent behavior"... may cover what you are thinking

I'm not entirely sure, they seem to be different concepts.

**Comment by AdamCraven** [comment]
Hey @dexterous , this is quite an open issue and I agree what you're saying is correct. It's going to take some research into the ideal format of linking principles and listing them in the graph. I'm going to close this, but even though it's closed it will be worked on. I may even start a discussion for public feedback https://github.com/PrinciplesDotDev/principles/discussions

Thanks again for taking the time. You're more than welcome to open again if you'd like to add more.
