### ISSUE TITLE
Principle: Apply Pressure

### ISSUE THREAD

**Issue by jamesarosen** [PrinciplesDotDev/principles#37]
I'll be happy to write this up as a pull-request if folks like it.

### The idea
Let pieces of the system put pressure on one another to help ensure correctness.

### Examples

* When refactoring, don't change both the tests and the code in the same commit. When refactoring the code, keep the tests fixed. When refactoring tests, keep the code fixed. You may alternate these in a single pull-request.
* When adding or replacing a system, roll it out gradually in production. The real-world usage will apply gradual pressure on your system. This will force you to add the necessary monitoring, resiliency, and other controls.

**Comment by AdamCraven** [comment]
Hi James - thanks for taking the time to put something together 👍 

I think I'm getting the meaning of "apply pressure". You're saying something along the lines of; keep yourself in a controlled situation, then use that to make the next change so you don't end up creating too much complexity? I found the second example harder to relate to the first example.

Is it similar in some ways to: https://principles.dev/p/iterate-in-thens/ (I don't mind having similar principles)?

To be able to add it to the site, you'll need to clearly explain the what and why is. At the moment it isn't super clear as to what "apply pressure" means or why you would want to use it. https://principles.dev/documentation/#quickstart-writing-your-first-principle

Let me know if you need any pointers.

**Comment by jamesarosen** [comment]
There's definitely some overlap with _iterate-in-thens_.

> I found the second example harder to relate to the first example.

Imagine you have a Cart and Checkout system and you want to modernize it in some substantial way. (Maybe you want to upgrade a framework or use a commercial off-the-shelf product for part of it.) Your system is already running and has some combination of users, conversion metrics, regular QA, synthetic performance tests, uptime monitoring, logging, etc.

If you swap out small pieces of the system gradually, each of those signals should remain relatively constant or improve.

If you swap out the whole system all at once, you're more likely to miss one of those important signals. Those signals are the "pressure" on your code, keeping it in place.

**Comment by AdamCraven** [comment]
It's a bit like an evolutionary pressure to adapt to the existing system.

Something along the lines of:

Ensure a system maintains correctness during change by using external forces (metrics, code, requirements) to ensure rapid adaption to its environment. (and probably lower cognitive load).

It doesn't matter if my interpretation is a little off and not what you were thinking. But I like your idea in general.

The principles writing process for me often goes through an evolution as I write and re-write it to distill the essence of it in the most clear way. I often come back to my principles again and again and edit them as I learn more.

You are more than welcome to add it to the site. It's a good one. 

Remember the two most important parts are the "what and the why". I think this one will need a few examples. Let me know if you need any help during the process.

**Comment by jamesarosen** [comment]
I wonder whether these are really two different (related) principles:
1. change the tests _or_ the code, but not both
2. make large changes gradually and monitor them

**Comment by AdamCraven** [comment]
I've reached that point many times before, realising that I might have more than one principle when I think about it. It's what's so valuable about distilling things into principles - it clarifies your thought process and teaches a lot about what you believe.

It's really up to you - how you split it up. It might be encapsulated under a single truth or multiple smaller ones. The smaller ones will tend to be more specific and immediately useful, whereas the insight gained from figuring out a larger principle can be much harder but can provide a deeper insight into code.

**Comment by AdamCraven** [comment]
Hi @jamesarosen, I'm going to close this issue for now. You are more than welcome to open back if there are further questions or submit your principle.
