### ISSUE TITLE
Broken Link for Login

### ISSUE THREAD

**Issue by SusieCarov** [PrinciplesDotDev/principles#53]
Clicking the LogIn/Sign Up page takes you to [this page](https://principles.dev/accounts/login/) where there is a big Sign In with GitHub button.

Clicking on the Sign In with GitHub button gives me a 404 page ([here](https://github.com/login/oauth/authorize?client_id=89ec2302b64da1215b8d+&redirect_uri=https%3A%2F%2Fprinciples.dev%2Faccounts%2Fgithub%2Flogin%2Fcallback%2F&scope=user%3Aemail&response_type=code&state=F1M0OjE9lhWb))

**Comment by AdamCraven** [comment]
Thank you for taking the time to point that out Susie - It has now been fixed 👍
